# Generated by Django 4.0.5 on 2022-06-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimagemodel',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is_deleted'),
        ),
    ]
