# Generated by Django 4.0.5 on 2022-06-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productmedia_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmedia',
            old_name='file',
            new_name='image',
        ),
    ]
