# Generated by Django 4.0.6 on 2022-07-10 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('original_name', models.TextField(blank=True, default=None, help_text='Original name')),
                ('core', models.FileField(upload_to='')),
                ('md5sum', models.CharField(max_length=32, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('removed_from_storage', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_optimized', models.BooleanField(db_index=True, default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('original_name', models.TextField(blank=True, default=None, help_text='Original name')),
                ('core', models.FileField(upload_to='')),
                ('md5sum', models.CharField(max_length=32, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('removed_from_storage', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_optimized', models.BooleanField(db_index=True, default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
                'abstract': False,
            },
        ),
    ]
