# Generated by Django 4.0.6 on 2022-07-10 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('file', '0002_alter_productfile_creator_userprofileimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileimage',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='userprofileimage',
            name='user',
        ),
        migrations.AlterField(
            model_name='productfile',
            name='md5sum',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='product.product'),
        ),
        migrations.DeleteModel(
            name='SimpleFile',
        ),
        migrations.DeleteModel(
            name='UserProfileImage',
        ),
    ]
